### ISSUE TITLE
Not working with version 0.5 of buttercms-python

### ISSUE THREAD

**Issue by gabriel4649** [ButterCMS/flask-cms-blog-example#1]
I am getting an error related with:

`response = client.posts.all(page=page, page_size=10)`

**Comment by rogerjin12** [comment]
@tatsuhirosatou Could you post the error you're getting?

**Comment by gabriel4649** [comment]
Sure!

![image](https://cloud.githubusercontent.com/assets/232527/21747586/ed228402-d538-11e6-8bbb-c141fc85c03b.png)

It works well with 0.3, just like in the example.

**Comment by rogerjin12** [comment]
@tatsuhirosatou Hmmm, the error in your screenshot is ``TypeError: all() got an unexpected keyword argument 'page'``, right?

I think that may just be because you're passing in `page` as an argument but that isn't a variable thats set earlier in your code (eg. could be set to `1`). Might this be the issue? Let me know if that resolves it or if I'm mis-interpreting it.

**Comment by rogerjin12** [comment]
@tatsuhirosatou Actually, I think you're right that there's a bug in the latest version of the python client. Could you use `0.3` for now? We'll get this fixed ASAP!

**Comment by gabriel4649** [comment]
Sure, I can use 0.3. Thanks for the quick reply.

2017年1月8日(日) 0:31 Roger Jin <notifications@github.com>:

**Comment by chasecoleman** [comment]
@rogerjin12 @tatsuhirosatou  The method signature changed in `0.5` to:
 `response = client.posts.all({'page': 1, 'page_size': 10})`

@tatsuhirosatou - can you give that a try?

I've updated this Flask example to call `.all()` correctly.

**Comment by gabriel4649** [comment]
@chasecoleman Yes, it works correctly now! Thanks
